config/routes.rb
Rails.application.routes.draw do
	mount ActionCable.server => '/cable'
  resources :users
  root "session#new"

  post '/session', to: "session#create"
  get '/home', to: "home#index"
  delete '/signout', to: "session#destroy"
  post 'msg', to: "message#create"
  post 'room', to: "message#create_room"
  post '/create_url', to: 'home#create_url'
  get '/:url_token', to: "home#short_url_redirect"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :room
	belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages
end

app/models/url.rb
class Url < ApplicationRecord
	before_create :generate_unique_token
	belongs_to :user

	validates :short_url_token, uniqueness: true

	def generate_unique_token
		self.short_url_token = SecureRandom.hex(4)
		generate_unique_token if self.class.exists?(short_url_token: self.short_url_token)
	end
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :username, presence: true, uniqueness: true

	has_many :messages
	has_many :urls
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper

  def redirect_to_homepage
  	redirect_to home_path if current_user.present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user, except: [:short_url_redirect]

	def index
		@users = User.where.not(id: current_user.id)
		if params[:room_id].present?
			room = Room.find_by(id: params[:room_id])
			if room.present? && room.users.include?(current_user.id.to_s)
				@messages = room.try(:messages).try("order","created_at")
				@users_name = User.where(id: room.users).pluck(:name).join(", ")
			else
				redirect_to home_path
			end
		else
			@urls = current_user.urls
		end
	end

	def urls
	end

	def create_url
		current_user.urls.create(original_url: params[:url_shortner][:url])
		redirect_to home_path
	end

	def short_url_redirect
		url = Url.find_by(short_url_token: params[:url_token]).try(:original_url)
		url = root_path unless url.present?
		redirect_to url
	end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController

	def create
		@room = Room.find_by(id: params[:message][:room_id])
		@message = Message.create(room_id: params[:message][:room_id], user_id: current_user.id, content: params[:message][:content])
		ConvoChannel.broadcast_to "room_#{@room.id}", @message
	end

	def create_room
		room = Room.select{|x| x.users.include?(current_user.id.to_s) && x.users.include?(params[:user])}.first
		room = Room.create(users: [current_user.id, params[:user].to_i]) if !room.present?
		redirect_to home_path(room_id: room)
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	before_action :redirect_to_homepage, only: [:new, :create]
	def new
	end

	def create
		user = User.find_by(username: params[:session][:username])
		if user.present? && user.authenticate(params[:session][:password])
			signin(user)
			redirect_to home_path
		else
			redirect_to root_path
		end
	end

	def destroy
		signout
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :redirect_to_homepage, only: [:new]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        signin(@user)
        format.html { redirect_to home_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        flash[:alert] = @user.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
    when :notice, "notice" then "alert alert-info"
    when :success, "success" then "alert alert-success"
    when :error, "error" then "alert alert-warning"
    when :alert, "alert" then "alert alert-danger"
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
	def signin(user)
		session[:user_id] = user.id
	end

	def current_user
		User.find_by(id: session[:user_id])
	end

	def authenticate_user
		redirect_to root_path if !current_user.present?
	end

	def signout
		session.delete(:user_id)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_chat.html.erb
<div class="chat_window">
  <div class="top_menu">
      <div class="title">Chat Room: <%= @users_name %></div>
  </div>
  <ul class="messages" id="chat_bx">
    <% @messages.each do |message| %>
      <li class="message <%= message.user_id == current_user.id ? 'right' : 'left' %> appeared">
          <div class="avatar"></div>
          <div class="text_wrapper">
              <div class="text"><%= message.content %></div>
          </div>
      </li>
    <% end %>
  </ul>
  <div class="bottom_wrapper clearfix">
    <%= hidden_field_tag :current_user_id, current_user.id %>
    <%= form_for :message, url: msg_path, html: {id: "chat_frm"} ,remote: true  do |f| %>
        <%= f.hidden_field :room_id, value: params[:room_id] %>
    <div class="message_input_wrapper">
        <%= f.text_field :content, class: "message_input", placeholder: "Type your message here..." %>
    </div>
    <div class="send_message">
        <div class="icon send_btn" style="font-size: 25px;">SEND</div>
    </div>
    <% end %>
  </div>
</div>
<div class="message_template">
    <li class="message">
        <div class="avatar"></div>
        <div class="text_wrapper">
            <div class="text"></div>
        </div>
    </li>
</div>

app/views/home/_urls.html.erb
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Short URL</th>
      <th scope="col">URL</th>
    </tr>
  </thead>
  <tbody>
    <% @urls.each_with_index do |url,i| %>
      <tr>
        <th scope="row"><%= i + 1 %></th>
        <td>
          <%= link_to root_url+url.short_url_token, target: "_blank" do %>
            <%= root_url+url.short_url_token %>
          <% end %>
        </td>
        <td>
          <%= link_to url.original_url, target: "_blank" do %>
            <%= url.original_url %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="login-wrap p-0">
  <%= form_for(:url_shortner, url: create_url_path, class: "signin-form") do |f| %>
    <div class="form-group">
      <%= f.text_field :url, autofocus: true, autocomplete: "Add your URL", placeholder: "Add your URL", class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= f.submit "Shorten URL", class: "form-control btn btn-primary submit px-3"%>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<% content_for :title, "Welcome #{current_user.name} | Reddit Daddy" %>
<div class="container d-flex align-items-stretch" style="padding-top: 74px;">
  <nav id="sidebar" class="img" style="background-image: url(/assets/login_bg.jpg);">
    <div class="p-4">
      <div style="text-align: center;">
        <h1><span class="logo">Chatter Box</span></h1>
      </div>
      <h1><span class="logo"><span>Friends List</span></span></h1>
      <ul class="list-unstyled components mb-5">
        <% @users.each do |user| %>
          <li class="active" style="display: flex;">
            <%= link_to user.name, room_path(user: user) ,style:"word-break: break-word;width: 90%;cursor: pointer;", method: :post %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="p-4">
      <div style="text-align: center;">
        <h1><span class="logo">URL Shortner</span></h1>
      </div>
      <a href="<%= home_path %>"><h1><span class="logo"><span>Visit Your URLs List</span></span></h1></a>
    </div>
  </nav>
  <% if params[:room_id].present? %>
    <div class="container" style="margin: 20px;" id="chat_section">
      <%= render "chat" %>
    </div>
  <% else %>
    <div class="container table-responsive" style="margin: 20px;" id="chat_section">
      <%= render "urls" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanetsparkApps</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    <%= favicon_link_tag asset_path('fav_icon.png') %>
  </head>

  <body>
  	<% if current_user.present? %>
      <%= render "shared/header" %>
    <% end %>
    <% flash.each do |type, msg| %>
      <div style="margin-top: 64px;" class="<%= flash_class(type) %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/session/new.html.erb
<% content_for :title, "Reddit Daddy" %>
<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center mb-5">
        <h1 class="heading-section">PlanetSpark</h1>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="login-wrap p-0">
          <%= link_to "Don't Have an account?", new_user_path, class: "mb-4 text-center h3_link" %>
          <%= form_for(:session, url: session_path, class: "signin-form") do |f| %>
            <div class="form-group">
              <%= f.text_field :username, autofocus: true, autocomplete: "Username", placeholder: "Username", class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder: "Password",required: true%>
              <span toggle="#password-field"></span>
            </div>
            <div class="form-group">
              <%= f.submit "Sign In", class: "form-control btn btn-primary submit px-3"%>
            </div>
            <div class="form-group d-md-flex">
              <div class="w-50 text-md-right">
                <%#= link_to "Forgot Password", new_password_path(resource_name), style: "color: #fff"%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<style>
  body{
    background-image: url(/assets/login_bg.jpg);
  }
</style>

app/views/shared/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg fixed-top py-3">
      <div class="container"><a href="<%= root_path %>" class="navbar-brand text-uppercase font-weight-bold">PlanetSpark</a>
      <span class="nav-item active" style="color: #fff;"><%= current_user.name %></span>
          <div id="navbarSupportedContent" class="collapse navbar-collapse">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item active"><%#= link_to "Home", root_path, class: "nav-link text-uppercase font-weight-bold" %></li>
                  <li class="nav-item active"><%#= link_to "Explore", home_explore_path, class: "nav-link text-uppercase font-weight-bold" %></li>
                  <li class="nav-item active"><%#= link_to "Posts", posts_path, class: "nav-link text-uppercase font-weight-bold" %></li>
                  <li class="nav-item"><%= link_to "Logout", signout_path, method: :delete, class: "nav-link text-uppercase font-weight-bold" %></li>
              </ul>
          </div>
      </div>
  </nav>
</header>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :confirm_password %>
    <%= f.text_field :confirm_password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password</th>
      <th>Confirm password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.confirm_password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "PlanetSpark" %>
<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center mb-5">
        <h1 class="heading-section">PlanetSpark</h1>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="login-wrap p-0">
          <span class="mb-4 text-center h3_link">Sign Up</span>
          <%= form_for(@user, class: "signin-form") do |f| %>
            <div class="form-group">
              <%= f.text_field :name, autofocus: true, autocomplete: "Name", placeholder: "Name", class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= f.text_field :username, autofocus: true, autocomplete: "Username", placeholder: "Username", class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder: "Password",required: true%>
              <span toggle="#password-field"></span>
            </div>
            <div class="form-group">
              <%= f.password_field :password_confirmation, autocomplete: "current-password", class: "form-control", placeholder: "Confirm Password", required: true%>
              <span toggle="#password-field"></span>
            </div>
            <div class="form-group">
              <%= f.submit "Sign Up", class: "form-control btn btn-primary submit px-3"%>
            </div>
            <div class="form-group d-md-flex">
                <%#= link_to "Sign In", new_session_path(resource_name), class: "mb-4 text-center h3_link"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<style>
  body{
    background-image: url(/assets/login_bg.jpg);
  }
</style>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Confirm password:</strong>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>